from binaryTree import BstNode, BinarySearchTree

bst = BinarySearchTree(25)
bst.insertValue(20)
bst.insertValue(15)
bst.insertValue(10)
bst.insertValue(9)
bst.insertValue(11)
bst.insertValue(18)
bst.insertValue(17)
bst.insertValue(50)
bst.insertValue(40)
bst.insertValue(47)
bst.insertValue(55)
bst.insertValue(27)
bst.insertValue(31)
bst.insertValue(23)
bst.insertValue(21)
bst.insertValue(20)
bst.insertValue(22)
bst.deleteValue(25)
bst.display()

from tree import Tree, TreeNode

print()
print()
print('TREE')
tree = Tree()
tree.insertValue(50)
tree.insertValue(25)
tree.insertValue(30)
tree.insertValue(10)
tree.display()

from kdTree import KdNode, KDTree

print()
print()
print('KD TREE')
kdt = KDTree(3)
kdt.insertValue((5, 9, 15))
kdt.insertValue((2, 15, 3))
kdt.insertValue((6, 4, 19))
kdt.insertValue((8, 18, 13))
kdt.insertValue((2, 3, 2))
kdt.insertValue((6, 12, 3))
kdt.insertValue((4, 7, 7))
kdt.insertValue((9, 9, 0))
kdt.insertValue((1, 11, 6))
kdt.display()
kdt.deleteValue((2, 15, 3))
print()
print()
print('DEL')
kdt.display()
